quarkus:
  http:
    port: 8081
  swagger-ui:
    path: /api-integracion-callmed
    always-include: true
    enable: true
    title: api-integracion-callmed
    description: API Documentation
  smallrye-openapi:
    enable: true
  rest-client:
    "com.fahorro.integracion.client.CallmedClient":
      url: https://www.winstondata.com.mx/SUSE2
      scope: javax.inject.Singleton

callmed:
  winstondata:
    user: usrFAPrueba
    password: W3bbHnn76
